In [1]:
import numpy as np

In [2]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
np.arange(2,100,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [7]:
np.ones(5) * 10

array([10., 10., 10., 10., 10.])

In [14]:
a = np.arange(1,17)



In [15]:
a.reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [16]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [31]:
np.random.random() * 5

2.98935516522124

In [33]:
np.random.randn(5,5)

array([[ 1.01887743e+00, -6.56686044e-01, -9.34611309e-01,
        -2.56567635e-01,  5.68622593e-01],
       [ 3.91744021e-01,  9.10845114e-01, -3.28260663e-01,
         1.73008262e+00, -3.74853429e-01],
       [-7.01576895e-01, -5.78646396e-04, -4.91511000e-01,
        -3.10923296e+00, -6.14815370e-01],
       [ 2.95491150e-01, -1.20875570e-02,  1.45680408e+00,
         6.42701825e-02,  3.45786008e-01],
       [ 7.79561395e-02,  1.25407060e+00, -1.99274074e-01,
         6.18224298e-01, -1.39032259e+00]])

In [34]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [35]:
arr = np.arange(1,101).reshape(10,10)

In [36]:
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [41]:
arr2 = arr[arr > 40]
arr2

array([ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,
        54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,
        67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,
        80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
        93,  94,  95,  96,  97,  98,  99, 100])

In [42]:
arr2.reshape(6,10)

array([[ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [45]:
arr[6:,4:]

array([[ 65,  66,  67,  68,  69,  70],
       [ 75,  76,  77,  78,  79,  80],
       [ 85,  86,  87,  88,  89,  90],
       [ 95,  96,  97,  98,  99, 100]])

In [48]:
arr[:3,2:4]

array([[ 3,  4],
       [13, 14],
       [23, 24]])

In [52]:
arr[:3,1:2].reshape(1,3)

array([[ 2, 12, 22]])

In [53]:
arr[:3,1:2]

array([[ 2],
       [12],
       [22]])

In [58]:
arr[:,-1]

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [59]:
arr1 = ((np.random.rand(9) * 5).astype(int)).reshape(3,3)
arr2 = ((np.random.rand(9) * 5).astype(int)).reshape(3,3)

In [60]:
arr1

array([[4, 4, 0],
       [2, 4, 2],
       [3, 4, 1]])

In [61]:
arr2

array([[4, 1, 1],
       [2, 3, 0],
       [2, 2, 0]])

In [62]:
arr1 + arr2

array([[8, 5, 1],
       [4, 7, 2],
       [5, 6, 1]])

In [63]:
arr1 * arr2

array([[16,  4,  0],
       [ 4, 12,  0],
       [ 6,  8,  0]])

In [65]:
(arr1 + arr2).mean()

4.333333333333333

In [66]:
arr1.sum()

24